// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sophon_patch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SophonPatchProto struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	PatchAssets   []*SophonPatchAssetProperty  `protobuf:"bytes,1,rep,name=PatchAssets,proto3" json:"PatchAssets,omitempty"`
	UnusedAssets  []*SophonUnusedAssetProperty `protobuf:"bytes,2,rep,name=UnusedAssets,proto3" json:"UnusedAssets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchProto) Reset() {
	*x = SophonPatchProto{}
	mi := &file_sophon_patch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchProto) ProtoMessage() {}

func (x *SophonPatchProto) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchProto.ProtoReflect.Descriptor instead.
func (*SophonPatchProto) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{0}
}

func (x *SophonPatchProto) GetPatchAssets() []*SophonPatchAssetProperty {
	if x != nil {
		return x.PatchAssets
	}
	return nil
}

func (x *SophonPatchProto) GetUnusedAssets() []*SophonUnusedAssetProperty {
	if x != nil {
		return x.UnusedAssets
	}
	return nil
}

type SophonPatchAssetProperty struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AssetName     string                  `protobuf:"bytes,1,opt,name=AssetName,proto3" json:"AssetName,omitempty"`
	AssetSize     int64                   `protobuf:"varint,2,opt,name=AssetSize,proto3" json:"AssetSize,omitempty"`
	AssetHashMd5  string                  `protobuf:"bytes,3,opt,name=AssetHashMd5,proto3" json:"AssetHashMd5,omitempty"`
	AssetInfos    []*SophonPatchAssetInfo `protobuf:"bytes,4,rep,name=AssetInfos,proto3" json:"AssetInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchAssetProperty) Reset() {
	*x = SophonPatchAssetProperty{}
	mi := &file_sophon_patch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchAssetProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchAssetProperty) ProtoMessage() {}

func (x *SophonPatchAssetProperty) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchAssetProperty.ProtoReflect.Descriptor instead.
func (*SophonPatchAssetProperty) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{1}
}

func (x *SophonPatchAssetProperty) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *SophonPatchAssetProperty) GetAssetSize() int64 {
	if x != nil {
		return x.AssetSize
	}
	return 0
}

func (x *SophonPatchAssetProperty) GetAssetHashMd5() string {
	if x != nil {
		return x.AssetHashMd5
	}
	return ""
}

func (x *SophonPatchAssetProperty) GetAssetInfos() []*SophonPatchAssetInfo {
	if x != nil {
		return x.AssetInfos
	}
	return nil
}

type SophonPatchAssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionTag    string                 `protobuf:"bytes,1,opt,name=VersionTag,proto3" json:"VersionTag,omitempty"`
	Chunk         *SophonPatchAssetChunk `protobuf:"bytes,2,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchAssetInfo) Reset() {
	*x = SophonPatchAssetInfo{}
	mi := &file_sophon_patch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchAssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchAssetInfo) ProtoMessage() {}

func (x *SophonPatchAssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchAssetInfo.ProtoReflect.Descriptor instead.
func (*SophonPatchAssetInfo) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{2}
}

func (x *SophonPatchAssetInfo) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *SophonPatchAssetInfo) GetChunk() *SophonPatchAssetChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type SophonPatchAssetChunk struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PatchName          string                 `protobuf:"bytes,1,opt,name=PatchName,proto3" json:"PatchName,omitempty"`
	VersionTag         string                 `protobuf:"bytes,2,opt,name=VersionTag,proto3" json:"VersionTag,omitempty"`
	BuildId            string                 `protobuf:"bytes,3,opt,name=BuildId,proto3" json:"BuildId,omitempty"`
	PatchSize          int64                  `protobuf:"varint,4,opt,name=PatchSize,proto3" json:"PatchSize,omitempty"`
	PatchMd5           string                 `protobuf:"bytes,5,opt,name=PatchMd5,proto3" json:"PatchMd5,omitempty"`
	PatchOffset        int64                  `protobuf:"varint,6,opt,name=PatchOffset,proto3" json:"PatchOffset,omitempty"`
	PatchLength        int64                  `protobuf:"varint,7,opt,name=PatchLength,proto3" json:"PatchLength,omitempty"`
	OriginalFileName   string                 `protobuf:"bytes,8,opt,name=OriginalFileName,proto3" json:"OriginalFileName,omitempty"`
	OriginalFileLength int64                  `protobuf:"varint,9,opt,name=OriginalFileLength,proto3" json:"OriginalFileLength,omitempty"`
	OriginalFileMd5    string                 `protobuf:"bytes,10,opt,name=OriginalFileMd5,proto3" json:"OriginalFileMd5,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SophonPatchAssetChunk) Reset() {
	*x = SophonPatchAssetChunk{}
	mi := &file_sophon_patch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchAssetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchAssetChunk) ProtoMessage() {}

func (x *SophonPatchAssetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchAssetChunk.ProtoReflect.Descriptor instead.
func (*SophonPatchAssetChunk) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{3}
}

func (x *SophonPatchAssetChunk) GetPatchName() string {
	if x != nil {
		return x.PatchName
	}
	return ""
}

func (x *SophonPatchAssetChunk) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *SophonPatchAssetChunk) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SophonPatchAssetChunk) GetPatchSize() int64 {
	if x != nil {
		return x.PatchSize
	}
	return 0
}

func (x *SophonPatchAssetChunk) GetPatchMd5() string {
	if x != nil {
		return x.PatchMd5
	}
	return ""
}

func (x *SophonPatchAssetChunk) GetPatchOffset() int64 {
	if x != nil {
		return x.PatchOffset
	}
	return 0
}

func (x *SophonPatchAssetChunk) GetPatchLength() int64 {
	if x != nil {
		return x.PatchLength
	}
	return 0
}

func (x *SophonPatchAssetChunk) GetOriginalFileName() string {
	if x != nil {
		return x.OriginalFileName
	}
	return ""
}

func (x *SophonPatchAssetChunk) GetOriginalFileLength() int64 {
	if x != nil {
		return x.OriginalFileLength
	}
	return 0
}

func (x *SophonPatchAssetChunk) GetOriginalFileMd5() string {
	if x != nil {
		return x.OriginalFileMd5
	}
	return ""
}

type SophonUnusedAssetProperty struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VersionTag    string                   `protobuf:"bytes,1,opt,name=VersionTag,proto3" json:"VersionTag,omitempty"`
	AssetInfos    []*SophonUnusedAssetInfo `protobuf:"bytes,2,rep,name=AssetInfos,proto3" json:"AssetInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonUnusedAssetProperty) Reset() {
	*x = SophonUnusedAssetProperty{}
	mi := &file_sophon_patch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonUnusedAssetProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonUnusedAssetProperty) ProtoMessage() {}

func (x *SophonUnusedAssetProperty) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonUnusedAssetProperty.ProtoReflect.Descriptor instead.
func (*SophonUnusedAssetProperty) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{4}
}

func (x *SophonUnusedAssetProperty) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *SophonUnusedAssetProperty) GetAssetInfos() []*SophonUnusedAssetInfo {
	if x != nil {
		return x.AssetInfos
	}
	return nil
}

type SophonUnusedAssetInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Assets        []*SophonUnusedAssetFile `protobuf:"bytes,1,rep,name=Assets,proto3" json:"Assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonUnusedAssetInfo) Reset() {
	*x = SophonUnusedAssetInfo{}
	mi := &file_sophon_patch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonUnusedAssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonUnusedAssetInfo) ProtoMessage() {}

func (x *SophonUnusedAssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonUnusedAssetInfo.ProtoReflect.Descriptor instead.
func (*SophonUnusedAssetInfo) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{5}
}

func (x *SophonUnusedAssetInfo) GetAssets() []*SophonUnusedAssetFile {
	if x != nil {
		return x.Assets
	}
	return nil
}

type SophonUnusedAssetFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	FileMd5       string                 `protobuf:"bytes,3,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonUnusedAssetFile) Reset() {
	*x = SophonUnusedAssetFile{}
	mi := &file_sophon_patch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonUnusedAssetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonUnusedAssetFile) ProtoMessage() {}

func (x *SophonUnusedAssetFile) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_patch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonUnusedAssetFile.ProtoReflect.Descriptor instead.
func (*SophonUnusedAssetFile) Descriptor() ([]byte, []int) {
	return file_sophon_patch_proto_rawDescGZIP(), []int{6}
}

func (x *SophonUnusedAssetFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SophonUnusedAssetFile) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SophonUnusedAssetFile) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

var File_sophon_patch_proto protoreflect.FileDescriptor

const file_sophon_patch_proto_rawDesc = "" +
	"\n" +
	"\x12sophon_patch.proto\x12\x17Hi3Helper.Sophon.Protos\"\xbf\x01\n" +
	"\x10SophonPatchProto\x12S\n" +
	"\vPatchAssets\x18\x01 \x03(\v21.Hi3Helper.Sophon.Protos.SophonPatchAssetPropertyR\vPatchAssets\x12V\n" +
	"\fUnusedAssets\x18\x02 \x03(\v22.Hi3Helper.Sophon.Protos.SophonUnusedAssetPropertyR\fUnusedAssets\"\xc9\x01\n" +
	"\x18SophonPatchAssetProperty\x12\x1c\n" +
	"\tAssetName\x18\x01 \x01(\tR\tAssetName\x12\x1c\n" +
	"\tAssetSize\x18\x02 \x01(\x03R\tAssetSize\x12\"\n" +
	"\fAssetHashMd5\x18\x03 \x01(\tR\fAssetHashMd5\x12M\n" +
	"\n" +
	"AssetInfos\x18\x04 \x03(\v2-.Hi3Helper.Sophon.Protos.SophonPatchAssetInfoR\n" +
	"AssetInfos\"|\n" +
	"\x14SophonPatchAssetInfo\x12\x1e\n" +
	"\n" +
	"VersionTag\x18\x01 \x01(\tR\n" +
	"VersionTag\x12D\n" +
	"\x05Chunk\x18\x02 \x01(\v2..Hi3Helper.Sophon.Protos.SophonPatchAssetChunkR\x05Chunk\"\xf3\x02\n" +
	"\x15SophonPatchAssetChunk\x12\x1c\n" +
	"\tPatchName\x18\x01 \x01(\tR\tPatchName\x12\x1e\n" +
	"\n" +
	"VersionTag\x18\x02 \x01(\tR\n" +
	"VersionTag\x12\x18\n" +
	"\aBuildId\x18\x03 \x01(\tR\aBuildId\x12\x1c\n" +
	"\tPatchSize\x18\x04 \x01(\x03R\tPatchSize\x12\x1a\n" +
	"\bPatchMd5\x18\x05 \x01(\tR\bPatchMd5\x12 \n" +
	"\vPatchOffset\x18\x06 \x01(\x03R\vPatchOffset\x12 \n" +
	"\vPatchLength\x18\a \x01(\x03R\vPatchLength\x12*\n" +
	"\x10OriginalFileName\x18\b \x01(\tR\x10OriginalFileName\x12.\n" +
	"\x12OriginalFileLength\x18\t \x01(\x03R\x12OriginalFileLength\x12(\n" +
	"\x0fOriginalFileMd5\x18\n" +
	" \x01(\tR\x0fOriginalFileMd5\"\x8b\x01\n" +
	"\x19SophonUnusedAssetProperty\x12\x1e\n" +
	"\n" +
	"VersionTag\x18\x01 \x01(\tR\n" +
	"VersionTag\x12N\n" +
	"\n" +
	"AssetInfos\x18\x02 \x03(\v2..Hi3Helper.Sophon.Protos.SophonUnusedAssetInfoR\n" +
	"AssetInfos\"_\n" +
	"\x15SophonUnusedAssetInfo\x12F\n" +
	"\x06Assets\x18\x01 \x03(\v2..Hi3Helper.Sophon.Protos.SophonUnusedAssetFileR\x06Assets\"i\n" +
	"\x15SophonUnusedAssetFile\x12\x1a\n" +
	"\bFileName\x18\x01 \x01(\tR\bFileName\x12\x1a\n" +
	"\bFileSize\x18\x02 \x01(\x03R\bFileSize\x12\x18\n" +
	"\aFileMd5\x18\x03 \x01(\tR\aFileMd5B4Z2omnigate/internal/providers/hoyoverse/sophon/protob\x06proto3"

var (
	file_sophon_patch_proto_rawDescOnce sync.Once
	file_sophon_patch_proto_rawDescData []byte
)

func file_sophon_patch_proto_rawDescGZIP() []byte {
	file_sophon_patch_proto_rawDescOnce.Do(func() {
		file_sophon_patch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sophon_patch_proto_rawDesc), len(file_sophon_patch_proto_rawDesc)))
	})
	return file_sophon_patch_proto_rawDescData
}

var file_sophon_patch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sophon_patch_proto_goTypes = []any{
	(*SophonPatchProto)(nil),          // 0: Hi3Helper.Sophon.Protos.SophonPatchProto
	(*SophonPatchAssetProperty)(nil),  // 1: Hi3Helper.Sophon.Protos.SophonPatchAssetProperty
	(*SophonPatchAssetInfo)(nil),      // 2: Hi3Helper.Sophon.Protos.SophonPatchAssetInfo
	(*SophonPatchAssetChunk)(nil),     // 3: Hi3Helper.Sophon.Protos.SophonPatchAssetChunk
	(*SophonUnusedAssetProperty)(nil), // 4: Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty
	(*SophonUnusedAssetInfo)(nil),     // 5: Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo
	(*SophonUnusedAssetFile)(nil),     // 6: Hi3Helper.Sophon.Protos.SophonUnusedAssetFile
}
var file_sophon_patch_proto_depIdxs = []int32{
	1, // 0: Hi3Helper.Sophon.Protos.SophonPatchProto.PatchAssets:type_name -> Hi3Helper.Sophon.Protos.SophonPatchAssetProperty
	4, // 1: Hi3Helper.Sophon.Protos.SophonPatchProto.UnusedAssets:type_name -> Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty
	2, // 2: Hi3Helper.Sophon.Protos.SophonPatchAssetProperty.AssetInfos:type_name -> Hi3Helper.Sophon.Protos.SophonPatchAssetInfo
	3, // 3: Hi3Helper.Sophon.Protos.SophonPatchAssetInfo.Chunk:type_name -> Hi3Helper.Sophon.Protos.SophonPatchAssetChunk
	5, // 4: Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty.AssetInfos:type_name -> Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo
	6, // 5: Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo.Assets:type_name -> Hi3Helper.Sophon.Protos.SophonUnusedAssetFile
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sophon_patch_proto_init() }
func file_sophon_patch_proto_init() {
	if File_sophon_patch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sophon_patch_proto_rawDesc), len(file_sophon_patch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sophon_patch_proto_goTypes,
		DependencyIndexes: file_sophon_patch_proto_depIdxs,
		MessageInfos:      file_sophon_patch_proto_msgTypes,
	}.Build()
	File_sophon_patch_proto = out.File
	file_sophon_patch_proto_goTypes = nil
	file_sophon_patch_proto_depIdxs = nil
}
