// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sophon_manifest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SophonManifestProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Assets        []*SophonManifestAssetProperty `protobuf:"bytes,1,rep,name=Assets,proto3" json:"Assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonManifestProto) Reset() {
	*x = SophonManifestProto{}
	mi := &file_sophon_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonManifestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonManifestProto) ProtoMessage() {}

func (x *SophonManifestProto) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonManifestProto.ProtoReflect.Descriptor instead.
func (*SophonManifestProto) Descriptor() ([]byte, []int) {
	return file_sophon_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *SophonManifestProto) GetAssets() []*SophonManifestAssetProperty {
	if x != nil {
		return x.Assets
	}
	return nil
}

type SophonManifestAssetProperty struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AssetName     string                      `protobuf:"bytes,1,opt,name=AssetName,proto3" json:"AssetName,omitempty"`
	AssetChunks   []*SophonManifestAssetChunk `protobuf:"bytes,2,rep,name=AssetChunks,proto3" json:"AssetChunks,omitempty"`
	AssetType     int32                       `protobuf:"varint,3,opt,name=AssetType,proto3" json:"AssetType,omitempty"`
	AssetSize     int64                       `protobuf:"varint,4,opt,name=AssetSize,proto3" json:"AssetSize,omitempty"`
	AssetHashMd5  string                      `protobuf:"bytes,5,opt,name=AssetHashMd5,proto3" json:"AssetHashMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonManifestAssetProperty) Reset() {
	*x = SophonManifestAssetProperty{}
	mi := &file_sophon_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonManifestAssetProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonManifestAssetProperty) ProtoMessage() {}

func (x *SophonManifestAssetProperty) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonManifestAssetProperty.ProtoReflect.Descriptor instead.
func (*SophonManifestAssetProperty) Descriptor() ([]byte, []int) {
	return file_sophon_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *SophonManifestAssetProperty) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *SophonManifestAssetProperty) GetAssetChunks() []*SophonManifestAssetChunk {
	if x != nil {
		return x.AssetChunks
	}
	return nil
}

func (x *SophonManifestAssetProperty) GetAssetType() int32 {
	if x != nil {
		return x.AssetType
	}
	return 0
}

func (x *SophonManifestAssetProperty) GetAssetSize() int64 {
	if x != nil {
		return x.AssetSize
	}
	return 0
}

func (x *SophonManifestAssetProperty) GetAssetHashMd5() string {
	if x != nil {
		return x.AssetHashMd5
	}
	return ""
}

type SophonManifestAssetChunk struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ChunkName                string                 `protobuf:"bytes,1,opt,name=ChunkName,proto3" json:"ChunkName,omitempty"`
	ChunkDecompressedHashMd5 string                 `protobuf:"bytes,2,opt,name=ChunkDecompressedHashMd5,proto3" json:"ChunkDecompressedHashMd5,omitempty"`
	ChunkOnFileOffset        int64                  `protobuf:"varint,3,opt,name=ChunkOnFileOffset,proto3" json:"ChunkOnFileOffset,omitempty"`
	ChunkSize                int64                  `protobuf:"varint,4,opt,name=ChunkSize,proto3" json:"ChunkSize,omitempty"`
	ChunkSizeDecompressed    int64                  `protobuf:"varint,5,opt,name=ChunkSizeDecompressed,proto3" json:"ChunkSizeDecompressed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SophonManifestAssetChunk) Reset() {
	*x = SophonManifestAssetChunk{}
	mi := &file_sophon_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonManifestAssetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonManifestAssetChunk) ProtoMessage() {}

func (x *SophonManifestAssetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sophon_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonManifestAssetChunk.ProtoReflect.Descriptor instead.
func (*SophonManifestAssetChunk) Descriptor() ([]byte, []int) {
	return file_sophon_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *SophonManifestAssetChunk) GetChunkName() string {
	if x != nil {
		return x.ChunkName
	}
	return ""
}

func (x *SophonManifestAssetChunk) GetChunkDecompressedHashMd5() string {
	if x != nil {
		return x.ChunkDecompressedHashMd5
	}
	return ""
}

func (x *SophonManifestAssetChunk) GetChunkOnFileOffset() int64 {
	if x != nil {
		return x.ChunkOnFileOffset
	}
	return 0
}

func (x *SophonManifestAssetChunk) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *SophonManifestAssetChunk) GetChunkSizeDecompressed() int64 {
	if x != nil {
		return x.ChunkSizeDecompressed
	}
	return 0
}

var File_sophon_manifest_proto protoreflect.FileDescriptor

const file_sophon_manifest_proto_rawDesc = "" +
	"\n" +
	"\x15sophon_manifest.proto\x12\x17Hi3Helper.Sophon.Protos\"c\n" +
	"\x13SophonManifestProto\x12L\n" +
	"\x06Assets\x18\x01 \x03(\v24.Hi3Helper.Sophon.Protos.SophonManifestAssetPropertyR\x06Assets\"\xf0\x01\n" +
	"\x1bSophonManifestAssetProperty\x12\x1c\n" +
	"\tAssetName\x18\x01 \x01(\tR\tAssetName\x12S\n" +
	"\vAssetChunks\x18\x02 \x03(\v21.Hi3Helper.Sophon.Protos.SophonManifestAssetChunkR\vAssetChunks\x12\x1c\n" +
	"\tAssetType\x18\x03 \x01(\x05R\tAssetType\x12\x1c\n" +
	"\tAssetSize\x18\x04 \x01(\x03R\tAssetSize\x12\"\n" +
	"\fAssetHashMd5\x18\x05 \x01(\tR\fAssetHashMd5\"\xf6\x01\n" +
	"\x18SophonManifestAssetChunk\x12\x1c\n" +
	"\tChunkName\x18\x01 \x01(\tR\tChunkName\x12:\n" +
	"\x18ChunkDecompressedHashMd5\x18\x02 \x01(\tR\x18ChunkDecompressedHashMd5\x12,\n" +
	"\x11ChunkOnFileOffset\x18\x03 \x01(\x03R\x11ChunkOnFileOffset\x12\x1c\n" +
	"\tChunkSize\x18\x04 \x01(\x03R\tChunkSize\x124\n" +
	"\x15ChunkSizeDecompressed\x18\x05 \x01(\x03R\x15ChunkSizeDecompressedB4Z2omnigate/internal/providers/hoyoverse/sophon/protob\x06proto3"

var (
	file_sophon_manifest_proto_rawDescOnce sync.Once
	file_sophon_manifest_proto_rawDescData []byte
)

func file_sophon_manifest_proto_rawDescGZIP() []byte {
	file_sophon_manifest_proto_rawDescOnce.Do(func() {
		file_sophon_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sophon_manifest_proto_rawDesc), len(file_sophon_manifest_proto_rawDesc)))
	})
	return file_sophon_manifest_proto_rawDescData
}

var file_sophon_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sophon_manifest_proto_goTypes = []any{
	(*SophonManifestProto)(nil),         // 0: Hi3Helper.Sophon.Protos.SophonManifestProto
	(*SophonManifestAssetProperty)(nil), // 1: Hi3Helper.Sophon.Protos.SophonManifestAssetProperty
	(*SophonManifestAssetChunk)(nil),    // 2: Hi3Helper.Sophon.Protos.SophonManifestAssetChunk
}
var file_sophon_manifest_proto_depIdxs = []int32{
	1, // 0: Hi3Helper.Sophon.Protos.SophonManifestProto.Assets:type_name -> Hi3Helper.Sophon.Protos.SophonManifestAssetProperty
	2, // 1: Hi3Helper.Sophon.Protos.SophonManifestAssetProperty.AssetChunks:type_name -> Hi3Helper.Sophon.Protos.SophonManifestAssetChunk
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sophon_manifest_proto_init() }
func file_sophon_manifest_proto_init() {
	if File_sophon_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sophon_manifest_proto_rawDesc), len(file_sophon_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sophon_manifest_proto_goTypes,
		DependencyIndexes: file_sophon_manifest_proto_depIdxs,
		MessageInfos:      file_sophon_manifest_proto_msgTypes,
	}.Build()
	File_sophon_manifest_proto = out.File
	file_sophon_manifest_proto_goTypes = nil
	file_sophon_manifest_proto_depIdxs = nil
}
